# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Attachment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Attachment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttachment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AttachmentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # Attachment
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Attachment
    def Family(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Attachment
    def BackendId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Attachment
    def Scheme(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Attachment
    def Locality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Attachment
    def Domain(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AttachmentStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    AttachmentStart(builder)

def AttachmentAddFamily(builder: flatbuffers.Builder, family: int):
    builder.PrependUint8Slot(0, family, 0)

def AddFamily(builder: flatbuffers.Builder, family: int):
    AttachmentAddFamily(builder, family)

def AttachmentAddBackendId(builder: flatbuffers.Builder, backendId: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(backendId), 0)

def AddBackendId(builder: flatbuffers.Builder, backendId: int):
    AttachmentAddBackendId(builder, backendId)

def AttachmentAddScheme(builder: flatbuffers.Builder, scheme: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(scheme), 0)

def AddScheme(builder: flatbuffers.Builder, scheme: int):
    AttachmentAddScheme(builder, scheme)

def AttachmentAddLocality(builder: flatbuffers.Builder, locality: int):
    builder.PrependUint8Slot(3, locality, 0)

def AddLocality(builder: flatbuffers.Builder, locality: int):
    AttachmentAddLocality(builder, locality)

def AttachmentAddDomain(builder: flatbuffers.Builder, domain: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(domain), 0)

def AddDomain(builder: flatbuffers.Builder, domain: int):
    AttachmentAddDomain(builder, domain)

def AttachmentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AttachmentEnd(builder)
