# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

class PayloadKind(object):
    Registration = 0
    ResourceUpdate = 1
    Deregistration = 2
    Snapshot = 3
