# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

class Payload(object):
    NONE = 0
    WorkerRegistration = 1
    WorkerResourceUpdate = 2
    WorkerDeregistration = 3
    WorkerRegistrySnapshot = 4
