# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from labios.registry.WorkerDescriptor import WorkerDescriptor
from typing import Optional
np = import_numpy()

class WorkerRegistrySnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerRegistrySnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerRegistrySnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerRegistrySnapshotBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerRegistrySnapshot
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerRegistrySnapshot
    def RegistryGeneration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerRegistrySnapshot
    def CapturedUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerRegistrySnapshot
    def Workers(self, j: int) -> Optional[WorkerDescriptor]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = WorkerDescriptor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorkerRegistrySnapshot
    def WorkersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerRegistrySnapshot
    def WorkersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def WorkerRegistrySnapshotStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    WorkerRegistrySnapshotStart(builder)

def WorkerRegistrySnapshotAddRegistryGeneration(builder: flatbuffers.Builder, registryGeneration: int):
    builder.PrependUint64Slot(0, registryGeneration, 0)

def AddRegistryGeneration(builder: flatbuffers.Builder, registryGeneration: int):
    WorkerRegistrySnapshotAddRegistryGeneration(builder, registryGeneration)

def WorkerRegistrySnapshotAddCapturedUs(builder: flatbuffers.Builder, capturedUs: int):
    builder.PrependUint64Slot(1, capturedUs, 0)

def AddCapturedUs(builder: flatbuffers.Builder, capturedUs: int):
    WorkerRegistrySnapshotAddCapturedUs(builder, capturedUs)

def WorkerRegistrySnapshotAddWorkers(builder: flatbuffers.Builder, workers: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(workers), 0)

def AddWorkers(builder: flatbuffers.Builder, workers: int):
    WorkerRegistrySnapshotAddWorkers(builder, workers)

def WorkerRegistrySnapshotStartWorkersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartWorkersVector(builder, numElems: int) -> int:
    return WorkerRegistrySnapshotStartWorkersVector(builder, numElems)

def WorkerRegistrySnapshotEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerRegistrySnapshotEnd(builder)
