# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from labios.registry.WorkerDescriptor import WorkerDescriptor
from typing import Optional
np = import_numpy()

class WorkerRegistration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerRegistration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerRegistration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerRegistrationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerRegistration
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerRegistration
    def Worker(self) -> Optional[WorkerDescriptor]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = WorkerDescriptor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WorkerRegistrationStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    WorkerRegistrationStart(builder)

def WorkerRegistrationAddWorker(builder: flatbuffers.Builder, worker: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(worker), 0)

def AddWorker(builder: flatbuffers.Builder, worker: int):
    WorkerRegistrationAddWorker(builder, worker)

def WorkerRegistrationEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerRegistrationEnd(builder)
