# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from labios.registry.Attachment import Attachment
from typing import Optional
np = import_numpy()

class WorkerDescriptor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerDescriptor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerDescriptor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerDescriptorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerDescriptor
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerDescriptor
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def RegistrationEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def RegistryGeneration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def Available(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # WorkerDescriptor
    def TotalCapacityBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def AvailableCapacityBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def Capacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerDescriptor
    def Load(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerDescriptor
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def Energy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def Tier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def MaxIrVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def Operations(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WorkerDescriptor
    def OperationsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def OperationsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # WorkerDescriptor
    def PipelineOperations(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WorkerDescriptor
    def PipelineOperationsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def PipelineOperationsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # WorkerDescriptor
    def Attachments(self, j: int) -> Optional[Attachment]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Attachment()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorkerDescriptor
    def AttachmentsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def AttachmentsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # WorkerDescriptor
    def LocalityDomains(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WorkerDescriptor
    def LocalityDomainsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def LocalityDomainsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # WorkerDescriptor
    def Skills(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerDescriptor
    def Compute(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerDescriptor
    def Reasoning(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerDescriptor
    def OperationVersions(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # WorkerDescriptor
    def OperationVersionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # WorkerDescriptor
    def OperationVersionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def OperationVersionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # WorkerDescriptor
    def PipelineOperationVersions(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # WorkerDescriptor
    def PipelineOperationVersionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # WorkerDescriptor
    def PipelineOperationVersionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerDescriptor
    def PipelineOperationVersionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        return o == 0

def WorkerDescriptorStart(builder: flatbuffers.Builder):
    builder.StartObject(21)

def Start(builder: flatbuffers.Builder):
    WorkerDescriptorStart(builder)

def WorkerDescriptorAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder: flatbuffers.Builder, id: int):
    WorkerDescriptorAddId(builder, id)

def WorkerDescriptorAddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    builder.PrependUint64Slot(1, registrationEpoch, 0)

def AddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    WorkerDescriptorAddRegistrationEpoch(builder, registrationEpoch)

def WorkerDescriptorAddRegistryGeneration(builder: flatbuffers.Builder, registryGeneration: int):
    builder.PrependUint64Slot(2, registryGeneration, 0)

def AddRegistryGeneration(builder: flatbuffers.Builder, registryGeneration: int):
    WorkerDescriptorAddRegistryGeneration(builder, registryGeneration)

def WorkerDescriptorAddAvailable(builder: flatbuffers.Builder, available: bool):
    builder.PrependBoolSlot(3, available, 0)

def AddAvailable(builder: flatbuffers.Builder, available: bool):
    WorkerDescriptorAddAvailable(builder, available)

def WorkerDescriptorAddTotalCapacityBytes(builder: flatbuffers.Builder, totalCapacityBytes: int):
    builder.PrependUint64Slot(4, totalCapacityBytes, 0)

def AddTotalCapacityBytes(builder: flatbuffers.Builder, totalCapacityBytes: int):
    WorkerDescriptorAddTotalCapacityBytes(builder, totalCapacityBytes)

def WorkerDescriptorAddAvailableCapacityBytes(builder: flatbuffers.Builder, availableCapacityBytes: int):
    builder.PrependUint64Slot(5, availableCapacityBytes, 0)

def AddAvailableCapacityBytes(builder: flatbuffers.Builder, availableCapacityBytes: int):
    WorkerDescriptorAddAvailableCapacityBytes(builder, availableCapacityBytes)

def WorkerDescriptorAddCapacity(builder: flatbuffers.Builder, capacity: float):
    builder.PrependFloat64Slot(6, capacity, 0.0)

def AddCapacity(builder: flatbuffers.Builder, capacity: float):
    WorkerDescriptorAddCapacity(builder, capacity)

def WorkerDescriptorAddLoad(builder: flatbuffers.Builder, load: float):
    builder.PrependFloat64Slot(7, load, 0.0)

def AddLoad(builder: flatbuffers.Builder, load: float):
    WorkerDescriptorAddLoad(builder, load)

def WorkerDescriptorAddSpeed(builder: flatbuffers.Builder, speed: int):
    builder.PrependUint8Slot(8, speed, 0)

def AddSpeed(builder: flatbuffers.Builder, speed: int):
    WorkerDescriptorAddSpeed(builder, speed)

def WorkerDescriptorAddEnergy(builder: flatbuffers.Builder, energy: int):
    builder.PrependUint8Slot(9, energy, 0)

def AddEnergy(builder: flatbuffers.Builder, energy: int):
    WorkerDescriptorAddEnergy(builder, energy)

def WorkerDescriptorAddTier(builder: flatbuffers.Builder, tier: int):
    builder.PrependUint8Slot(10, tier, 0)

def AddTier(builder: flatbuffers.Builder, tier: int):
    WorkerDescriptorAddTier(builder, tier)

def WorkerDescriptorAddMaxIrVersion(builder: flatbuffers.Builder, maxIrVersion: int):
    builder.PrependUint32Slot(11, maxIrVersion, 0)

def AddMaxIrVersion(builder: flatbuffers.Builder, maxIrVersion: int):
    WorkerDescriptorAddMaxIrVersion(builder, maxIrVersion)

def WorkerDescriptorAddOperations(builder: flatbuffers.Builder, operations: int):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(operations), 0)

def AddOperations(builder: flatbuffers.Builder, operations: int):
    WorkerDescriptorAddOperations(builder, operations)

def WorkerDescriptorStartOperationsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOperationsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartOperationsVector(builder, numElems)

def WorkerDescriptorAddPipelineOperations(builder: flatbuffers.Builder, pipelineOperations: int):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineOperations), 0)

def AddPipelineOperations(builder: flatbuffers.Builder, pipelineOperations: int):
    WorkerDescriptorAddPipelineOperations(builder, pipelineOperations)

def WorkerDescriptorStartPipelineOperationsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPipelineOperationsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartPipelineOperationsVector(builder, numElems)

def WorkerDescriptorAddAttachments(builder: flatbuffers.Builder, attachments: int):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(attachments), 0)

def AddAttachments(builder: flatbuffers.Builder, attachments: int):
    WorkerDescriptorAddAttachments(builder, attachments)

def WorkerDescriptorStartAttachmentsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartAttachmentsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartAttachmentsVector(builder, numElems)

def WorkerDescriptorAddLocalityDomains(builder: flatbuffers.Builder, localityDomains: int):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(localityDomains), 0)

def AddLocalityDomains(builder: flatbuffers.Builder, localityDomains: int):
    WorkerDescriptorAddLocalityDomains(builder, localityDomains)

def WorkerDescriptorStartLocalityDomainsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartLocalityDomainsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartLocalityDomainsVector(builder, numElems)

def WorkerDescriptorAddSkills(builder: flatbuffers.Builder, skills: float):
    builder.PrependFloat64Slot(16, skills, 0.0)

def AddSkills(builder: flatbuffers.Builder, skills: float):
    WorkerDescriptorAddSkills(builder, skills)

def WorkerDescriptorAddCompute(builder: flatbuffers.Builder, compute: float):
    builder.PrependFloat64Slot(17, compute, 0.0)

def AddCompute(builder: flatbuffers.Builder, compute: float):
    WorkerDescriptorAddCompute(builder, compute)

def WorkerDescriptorAddReasoning(builder: flatbuffers.Builder, reasoning: int):
    builder.PrependUint8Slot(18, reasoning, 0)

def AddReasoning(builder: flatbuffers.Builder, reasoning: int):
    WorkerDescriptorAddReasoning(builder, reasoning)

def WorkerDescriptorAddOperationVersions(builder: flatbuffers.Builder, operationVersions: int):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(operationVersions), 0)

def AddOperationVersions(builder: flatbuffers.Builder, operationVersions: int):
    WorkerDescriptorAddOperationVersions(builder, operationVersions)

def WorkerDescriptorStartOperationVersionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOperationVersionsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartOperationVersionsVector(builder, numElems)

def WorkerDescriptorAddPipelineOperationVersions(builder: flatbuffers.Builder, pipelineOperationVersions: int):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineOperationVersions), 0)

def AddPipelineOperationVersions(builder: flatbuffers.Builder, pipelineOperationVersions: int):
    WorkerDescriptorAddPipelineOperationVersions(builder, pipelineOperationVersions)

def WorkerDescriptorStartPipelineOperationVersionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPipelineOperationVersionsVector(builder, numElems: int) -> int:
    return WorkerDescriptorStartPipelineOperationVersionsVector(builder, numElems)

def WorkerDescriptorEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerDescriptorEnd(builder)
