# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

class WorkerRegistryMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerRegistryMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerRegistryMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerRegistryMessageBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerRegistryMessage
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerRegistryMessage
    def ProtocolVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # WorkerRegistryMessage
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WorkerRegistryMessage
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerRegistryMessage
    def Payload(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WorkerRegistryMessageStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    WorkerRegistryMessageStart(builder)

def WorkerRegistryMessageAddProtocolVersion(builder: flatbuffers.Builder, protocolVersion: int):
    builder.PrependUint32Slot(0, protocolVersion, 0)

def AddProtocolVersion(builder: flatbuffers.Builder, protocolVersion: int):
    WorkerRegistryMessageAddProtocolVersion(builder, protocolVersion)

def WorkerRegistryMessageAddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependInt8Slot(1, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    WorkerRegistryMessageAddKind(builder, kind)

def WorkerRegistryMessageAddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    builder.PrependUint8Slot(2, payloadType, 0)

def AddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    WorkerRegistryMessageAddPayloadType(builder, payloadType)

def WorkerRegistryMessageAddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    WorkerRegistryMessageAddPayload(builder, payload)

def WorkerRegistryMessageEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerRegistryMessageEnd(builder)
