# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class WorkerResourceUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerResourceUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerResourceUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerResourceUpdateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerResourceUpdate
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerResourceUpdate
    def WorkerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorkerResourceUpdate
    def RegistrationEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerResourceUpdate
    def Available(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # WorkerResourceUpdate
    def TotalCapacityBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerResourceUpdate
    def AvailableCapacityBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerResourceUpdate
    def Capacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerResourceUpdate
    def Load(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerResourceUpdate
    def Skills(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerResourceUpdate
    def Compute(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # WorkerResourceUpdate
    def Reasoning(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def WorkerResourceUpdateStart(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    WorkerResourceUpdateStart(builder)

def WorkerResourceUpdateAddWorkerId(builder: flatbuffers.Builder, workerId: int):
    builder.PrependInt32Slot(0, workerId, 0)

def AddWorkerId(builder: flatbuffers.Builder, workerId: int):
    WorkerResourceUpdateAddWorkerId(builder, workerId)

def WorkerResourceUpdateAddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    builder.PrependUint64Slot(1, registrationEpoch, 0)

def AddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    WorkerResourceUpdateAddRegistrationEpoch(builder, registrationEpoch)

def WorkerResourceUpdateAddAvailable(builder: flatbuffers.Builder, available: bool):
    builder.PrependBoolSlot(2, available, 0)

def AddAvailable(builder: flatbuffers.Builder, available: bool):
    WorkerResourceUpdateAddAvailable(builder, available)

def WorkerResourceUpdateAddTotalCapacityBytes(builder: flatbuffers.Builder, totalCapacityBytes: int):
    builder.PrependUint64Slot(3, totalCapacityBytes, 0)

def AddTotalCapacityBytes(builder: flatbuffers.Builder, totalCapacityBytes: int):
    WorkerResourceUpdateAddTotalCapacityBytes(builder, totalCapacityBytes)

def WorkerResourceUpdateAddAvailableCapacityBytes(builder: flatbuffers.Builder, availableCapacityBytes: int):
    builder.PrependUint64Slot(4, availableCapacityBytes, 0)

def AddAvailableCapacityBytes(builder: flatbuffers.Builder, availableCapacityBytes: int):
    WorkerResourceUpdateAddAvailableCapacityBytes(builder, availableCapacityBytes)

def WorkerResourceUpdateAddCapacity(builder: flatbuffers.Builder, capacity: float):
    builder.PrependFloat64Slot(5, capacity, 0.0)

def AddCapacity(builder: flatbuffers.Builder, capacity: float):
    WorkerResourceUpdateAddCapacity(builder, capacity)

def WorkerResourceUpdateAddLoad(builder: flatbuffers.Builder, load: float):
    builder.PrependFloat64Slot(6, load, 0.0)

def AddLoad(builder: flatbuffers.Builder, load: float):
    WorkerResourceUpdateAddLoad(builder, load)

def WorkerResourceUpdateAddSkills(builder: flatbuffers.Builder, skills: float):
    builder.PrependFloat64Slot(7, skills, 0.0)

def AddSkills(builder: flatbuffers.Builder, skills: float):
    WorkerResourceUpdateAddSkills(builder, skills)

def WorkerResourceUpdateAddCompute(builder: flatbuffers.Builder, compute: float):
    builder.PrependFloat64Slot(8, compute, 0.0)

def AddCompute(builder: flatbuffers.Builder, compute: float):
    WorkerResourceUpdateAddCompute(builder, compute)

def WorkerResourceUpdateAddReasoning(builder: flatbuffers.Builder, reasoning: int):
    builder.PrependUint8Slot(9, reasoning, 0)

def AddReasoning(builder: flatbuffers.Builder, reasoning: int):
    WorkerResourceUpdateAddReasoning(builder, reasoning)

def WorkerResourceUpdateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerResourceUpdateEnd(builder)
