# automatically generated by the FlatBuffers compiler, do not modify

# namespace: registry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class WorkerDeregistration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerDeregistration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerDeregistration(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorkerDeregistrationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4C\x57\x52\x32", size_prefixed=size_prefixed)

    # WorkerDeregistration
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerDeregistration
    def WorkerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # WorkerDeregistration
    def RegistrationEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def WorkerDeregistrationStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    WorkerDeregistrationStart(builder)

def WorkerDeregistrationAddWorkerId(builder: flatbuffers.Builder, workerId: int):
    builder.PrependInt32Slot(0, workerId, 0)

def AddWorkerId(builder: flatbuffers.Builder, workerId: int):
    WorkerDeregistrationAddWorkerId(builder, workerId)

def WorkerDeregistrationAddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    builder.PrependUint64Slot(1, registrationEpoch, 0)

def AddRegistrationEpoch(builder: flatbuffers.Builder, registrationEpoch: int):
    WorkerDeregistrationAddRegistrationEpoch(builder, registrationEpoch)

def WorkerDeregistrationEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WorkerDeregistrationEnd(builder)
