// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REQUEST_H_
#define FLATBUFFERS_GENERATED_REQUEST_H_

#include "flatbuffers/flatbuffers.h"

struct posix_api_request;

enum posix_request_type {
  posix_request_type_OPEN = 0,
  posix_request_type_CLOSE = 1,
  posix_request_type_READ = 2,
  posix_request_type_WRITE = 3,
  posix_request_type_MIN = posix_request_type_OPEN,
  posix_request_type_MAX = posix_request_type_WRITE
};

inline const char **EnumNamesposix_request_type() {
  static const char *names[] = {
    "OPEN",
    "CLOSE",
    "READ",
    "WRITE",
    nullptr
  };
  return names;
}

inline const char *EnumNameposix_request_type(posix_request_type e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesposix_request_type()[index];
}

MANUALLY_ALIGNED_STRUCT(8) posix_api_request FLATBUFFERS_FINAL_CLASS {
 private:
  int8_t type_;
  int8_t padding0__;  int16_t padding1__;  int32_t padding2__;
  int64_t offset_;
  uint32_t size_;
  int32_t fd_;

 public:
  posix_api_request() {
    memset(this, 0, sizeof(posix_api_request));
  }
  posix_api_request(const posix_api_request &_o) {
    memcpy(this, &_o, sizeof(posix_api_request));
  }
  posix_api_request(posix_request_type _type, int64_t _offset, uint32_t _size, int32_t _fd)
      : type_(flatbuffers::EndianScalar(static_cast<int8_t>(_type))),
        padding0__(0),
        padding1__(0),
        padding2__(0),
        offset_(flatbuffers::EndianScalar(_offset)),
        size_(flatbuffers::EndianScalar(_size)),
        fd_(flatbuffers::EndianScalar(_fd)) {
    (void)padding0__;    (void)padding1__;    (void)padding2__;
  }
  posix_request_type type() const {
    return static_cast<posix_request_type>(flatbuffers::EndianScalar(type_));
  }
  int64_t offset() const {
    return flatbuffers::EndianScalar(offset_);
  }
  uint32_t size() const {
    return flatbuffers::EndianScalar(size_);
  }
  int32_t fd() const {
    return flatbuffers::EndianScalar(fd_);
  }
};
STRUCT_END(posix_api_request, 24);

#endif  // FLATBUFFERS_GENERATED_REQUEST_H_
